#! /bin/sh
# postinst script for tenshi

set -e

case "$1" in
    configure)
      if ! getent passwd tenshi 2>&1 >/dev/null; then
         # the account doesn't exist... time to create it
         echo -n "Adding tenshi system user.."
         adduser --quiet --system --group --home /var/run/tenshi tenshi
         echo ".done"
         adduser --quiet tenshi adm
      fi

      chown tenshi:root /etc/tenshi/tenshi.conf
      chown tenshi:root /var/run/tenshi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#
#DEBHELPER#
#

exit 0


