#! /bin/sh
# postinst script for tenshi
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
#


case "$1" in
    configure)
      if ! id -u tenshi >/dev/null 2>&1 ; then
         # the account doesn't exist... time to create it
         echo "creating Tenshi system user..."
         adduser --quiet --system --group --home /var/run/tenshi tenshi
				 adduser tenshi adm
      fi

      chown tenshi:root /etc/tenshi/tenshi.conf
      chown tenshi:root /var/run/tenshi  
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#
#DEBHELPER#
#

exit 0


