#! /bin/sh
# preinst script for tenshi

set -e

case "$1" in
    install)
    ;;

    upgrade)
        if [ -x "/etc/init.d/tenshi" ]; then
            if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
                    invoke-rc.d tenshi stop || exit $?
            else
                    /etc/init.d/tenshi stop || exit $?
            fi
         fi
    ;;

    abort-upgrade)
    ;;   

*)
    echo "preinst called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
